### ISSUE TITLE
Cannot get the popup to show

### ISSUE THREAD

**Issue by tempus2016** [strange-v/roborock-vacuum-card#13]
Installed this today with a roborock s7 max ultra.  Edited the card to match my entities and area id's but getting a couple of errors.  Any idea what is causing them?

```
Uncaught TypeError: this.robot.getSuctionMode is not a function
    at oe.connectedCallback (roborock-vacuum-card.js?hacstag=781856927130:4:29120)
    at X.S (roborock-vacuum-card.js?hacstag=781856927130:1:11458)
    at X.T (roborock-vacuum-card.js?hacstag=781856927130:1:11532)
    at X.$ (roborock-vacuum-card.js?hacstag=781856927130:1:11877)
    at X._$AI (roborock-vacuum-card.js?hacstag=781856927130:1:11316)
    at G.p (roborock-vacuum-card.js?hacstag=781856927130:1:10765)
    at X.$ (roborock-vacuum-card.js?hacstag=781856927130:1:11813)
    at X._$AI (roborock-vacuum-card.js?hacstag=781856927130:1:11316)
    at roborock-vacuum-card.js?hacstag=781856927130:1:14570
    at ie.update (roborock-vacuum-card.js?hacstag=781856927130:1:14581)Understand this errorAI
roborock-vacuum-card.js?hacstag=781856927130:4 
```

```
Uncaught (in promise) TypeError: this.areas.map is not a function
    at oe.renderAreas (roborock-vacuum-card.js?hacstag=781856927130:4:33262)
    at oe.render (roborock-vacuum-card.js?hacstag=781856927130:4:30677)
    at oe.update (roborock-vacuum-card.js?hacstag=781856927130:1:14298)
    at oe.performUpdate (roborock-vacuum-card.js?hacstag=781856927130:1:6595)
    at oe.scheduleUpdate (roborock-vacuum-card.js?hacstag=781856927130:1:6131)
    at oe._$ET (roborock-vacuum-card.js?hacstag=781856927130:1:6039)
```
```

type: custom:roborock-vacuum-card
entity: vacuum.s7_max_ultra
stats:
  default:
    - entity: sensor.s7_max_ultra_filter_time_left
      divide_by: 3600
      scale: 1
      title: Filter
      unit: h
    - entity: sensor.s7_max_ultra_side_brush_time_left
      divide_by: 3600
      scale: 1
      title: Side brush
      unit: h
    - entity: sensor.s7_max_ultra_main_brush_time_left
      divide_by: 3600
      scale: 1
      unit: h
      title: Main brush
    - entity: sensor.s7_max_ultra_sensor_time_left
      divide_by: 3600
      scale: 1
      unit: h
      title: Sensors
  cleaning:
    - entity: sensor.s7_max_ultra_cleaning_progress
      title: Cleaning progress
      unit: "%"
    - entity: sensor.s7_max_ultra_cleaning_area
      title: Cleaning area
      unit: m²
    - entity: sensor.s7_max_ultra_cleaning_time
      divide_by: 60
      scale: 1
      title: Cleaning time
      unit: min
areas:
  - area_id: hall
    roborock_area_id: 17
  - area_id: living_room
    roborock_area_id: 18

```
