### ISSUE TITLE
Limited "area_id" titles

### ISSUE THREAD

**Issue by AlanMW** [strange-v/roborock-vacuum-card#4]
I have a few rooms that don't have the same area_id's that you used, so when I put in my own names they don't show up in the list of options. For example, an area_id of "master_bathroom" would prevent my room from showing up. Any way it could be tweaked so it could take in any name?

Some info

```
vacuum.roborock_qrevo_pro:
  maps:
    - flag: 0
      name: Map_Primary
      rooms:
        "16": Guest Bathroom
        "17": Master Bathroom
        "18": Master bedroom
        "19": Hall
        "20": John's Office
        "21": Bedroom
        "22": Living room
        "23": Basement
        "24": Kitchen
        "25": Dining room
```

My area config

```
areas:
  - area_id: guest_bathroom
    roborock_area_id: 16
  - area_id: master_bathroom
    roborock_area_id: 17
  - area_id: master_bedroom
    roborock_area_id: 18
  - area_id: hall
    roborock_area_id: 19
  - area_id: John's Office
    roborock_area_id: 20
  - area_id: bedroom
    roborock_area_id: 21
  - area_id: living_room
    roborock_area_id: 22
  - area_id: kitchen
    roborock_area_id: 24
  - area_id: dining_room
    roborock_area_id: 25
```

What I see 

<img width="978" alt="Image" src="https://github.com/user-attachments/assets/8b64890e-6d2c-49f6-b8a8-0bd840acc32f" />
