### ISSUE TITLE
Cannot see areas in pop-up

### ISSUE THREAD

**Issue by xmatr1x69** [strange-v/roborock-vacuum-card#9]
Hi, I have qrevo master (edited all things to work), but I cant see areas. I had yours areas as well as mine with correct IDs. Im not good at coding, so its not that easy to find a problem. What should I show you?

**Comment by xmatr1x69** [comment]
![Image](https://github.com/user-attachments/assets/8aa9ed35-31ea-4247-bb5d-78b52ba42626)
I cant see three icons on the top either...
![Image](https://github.com/user-attachments/assets/ea59e077-ef62-4bd5-9684-adc6142217f6)
Thats the pop up

```
type: custom:roborock-vacuum-card
entity: vacuum.roborock_qrevo_master
stats:
  default:
    - entity: sensor.roborock_qrevo_master_pozostal_czas_filtrowania
      scale: 1
      title: Filtr
      unit: h
    - entity: sensor.roborock_qrevo_master_pozostal_czas_szczotki_bocznej
      scale: 1
      title: Boczna szczotka
      unit: h
    - entity: sensor.roborock_qrevo_master_pozostal_czas_szczotki_glownej
      scale: 1
      unit: h
      title: Główna szczotka
    - entity: sensor.roborock_qrevo_master_pozostal_czas_czujnika
      scale: 1
      unit: h
      title: Czujniki
  cleaning:
    - entity: sensor.roborock_qrevo_master_cleaning_progress
      title: Postęp sprzątania
      unit: "%"
    - entity: sensor.roborock_qrevo_master_obszar_sprzatania
      title: Obszar sprzątania
      unit: m²
    - entity: sensor.roborock_qrevo_master_czas_czyszczenia
      scale: 1
      title: Czas sprzątania
      unit: min
areas:
  - area_id: kitchen
    roborock_area_id: 15
```
This is my card config
